name: ZAP
on:
  # run on every pull request
  # pull_request:

  # run when pushed to main
  # push:
  #   branches: ["main"]

  # run on a schedule
  # schedule:
  # Run every Wednesday on 00:00
  #   - cron: "0 0 * * 3"

  # enable to run it manually
  workflow_dispatch:
    inputs:
      url:
        description: "URL to scan"
        required: true
        default: "https://www.mvdam.dev"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: ${{ github.event.inputs.url }}
