name: ZAP
on:
  workflow_dispatch:
    inputs:
      url:
        description: "URL to scan"
        required: true
        default: "https://www.mvdam.dev"

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.13.0
        with:
          target: ${{ github.event.inputs.url }}
